### PR TITLE
Renamed the bin_age column and print_devider method

### PR DESCRIPTION
**Pull request by AdesholaAfolabi**
- Modified the newly created column in bin_age method from transformed_age to bin_age
-  Renamed print_devider to print_divider across all modules and methods

### CODE REVIEW

**Comment by AdesholaAfolabi** [comment]
@Justus-coded @Sensei-akin 

It's strange I can't add you guys as reviewers in the dropdown. Here are a few changes that I have made, I am still doing some more stuff.

**Comment by Justus-coded** [comment]
Alright. 

Would be making a PR soon.

**Comment by Sensei-akin** [comment]
@AdesholaAfolabi I think only you can merge pull requests.

**Comment by Sensei-akin** [comment]
@Justus-coded Before you make a PR. Please don't forget to make a pull request with the recent changes that @AdesholaAfolabi made

**Comment by AdesholaAfolabi** [comment]
Yeah, you should pull from the staging branch.

**Pull request merged**
