### PR TITLE
Updated slik-wrangler UI app

### PR DESCRIPTION
**Pull request by ganiyuolalekan**
Many changes have been made to the UI design, and here is a quick note on how to navigate this slik-wrangler UI design. The navigation is now different. The mode to run the package now is by running 3 streamlit python files

* The `index.py` file first
* The `getting_started.py` file second
* The `team.py` file third

The `index.py` file serves as the header file and should be the first to be accessed... the rest is pretty much straightforward.

### CODE REVIEW

**Comment by AdesholaAfolabi** [comment]
@ganiyuolalekan just for clarity, do we need to run the files one after the other?
FYI Remember to always add the other guys as reviewers.

**Comment by ganiyuolalekan** [comment]
@AdesholaAfolabi I tried adding others I couldn't because I didn't know how... now that I think of it I could have just google searched 😅

Anyways, about the files... they should be run on 3 separate terminals but in the order I stated

@Justus-coded @Sensei-akin

**Comment by Justus-coded** [comment]
Well done @ganiyuolalekan. This is really good work. 

I have gone through the codes but I feel you need to explain how all these tie in together. 

As regards testing, I haven't tested yet. Seems like @AdesholaAfolabi has to merge first so we can pull. 

Or are there other ways of getting new changes asides from cloning your @ganiyuolalekan repo? 

cc: @Sensei-akin

**Comment by ganiyuolalekan** [comment]
Thanks @Justus-coded , I hoped we could meet earlier for me to explain the changes, but since it is Monday already, we could just wait till Wednesday by 6 pm.

For trying out the code though, I don't know of any other way aside cloning the changes from my repo, but that should suffix for checking out how it works.

CC: @Sensei-akin

**Comment by AdesholaAfolabi** [comment]
Just merged @Justus-coded @ganiyuolalekan

**Pull request merged**
